### ISSUE TITLE
Quick Question: what is the difference between 'vm trace step' and 'execution step'?

### ISSUE THREAD

**Issue by charlesxsh** [ethereum/remix-project#3943]
In most cases, their number are pretty close. Sometime they are different:

```
vm trace step:
148523
execution step:
81256
``` 

I thought one opcode is one step. But why VM trace step can be different from execution step?

**Comment by fwx5618177** [comment]
Could you paste or upload some detail info?

**Comment by charlesxsh** [comment]
Sure. 

In Remix IDE, When I deployed Tester and call call_test9, then start debugging that transaction, I have the different VM trace step and execution step shown at the debugger

```
contract Dummy {
    function test7(uint256[] memory amounts) internal {
    }
    
    function test9(uint256[] memory amounts) external {
        test7(amounts);
    }

    function test10(uint256[] calldata amounts) external {
        test7(amounts);
    }
}


contract Tester {
    Dummy d = new Dummy();

    function call_test9() external {
        uint256[] memory data = new uint256[](1000);
        d.test9(data);
    }

    function call_test10() external {
        uint256[] memory data = new uint256[](1000);
        d.test10(data);
    }
}
```

@fwx5618177

**Comment by fwx5618177** [comment]
@charlesxsh Could you share the screenshots, I can't reproduce it.

**Comment by charlesxsh** [comment]
Deployed Tester and called call_test9
<img width="768" alt="Screenshot 2023-07-25 at 5 00 51 AM" src="https://github.com/ethereum/remix-project/assets/8362565/edbeeeb2-6761-4e98-9ac9-8d91384f9f39">

Here is the debugger "Step details" section, debug the transaction about call_test9 and the number is right after call_test9 execution.
<img width="272" alt="Screenshot 2023-07-25 at 5 00 00 AM" src="https://github.com/ethereum/remix-project/assets/8362565/a15f5848-57a2-47ee-878f-82cabc78bc88">

@fwx5618177

**Comment by fwx5618177** [comment]
> Deployed Tester and called call_test9 <img alt="Screenshot 2023-07-25 at 5 00 51 AM" width="768" src="https://user-images.githubusercontent.com/8362565/255848203-edbeeeb2-6761-4e98-9ac9-8d91384f9f39.png">
> 
> Here is the debugger "Step details" section, debug the transaction about call_test9 and the number is right after call_test9 execution. <img alt="Screenshot 2023-07-25 at 5 00 00 AM" width="272" src="https://user-images.githubusercontent.com/8362565/255848200-a15f5848-57a2-47ee-878f-82cabc78bc88.png">
> 
> @fwx5618177

Still can't trace the exact location. Maybe need help. @Aniket-Engg

**Comment by yann300** [comment]
"vm trace step" represents the index in the complete vm trace.
"execution step" reprensents the current index with regard to the current internal call.
